### ISSUE TITLE
Question: How do you run stylelint?

### ISSUE THREAD

**Issue by zenflow** [ericwindmill/gatsby-starter-docs#5]
I see that that `stylelint` is a devDependency here, but I cannot figure out how it get's run... What am I missing?

Thanks for the sweet starter pack! 🥂

**Comment by levino** [comment]
You should be good with this: https://github.com/styled-components/stylelint-processor-styled-components

I would say style linting is not in the scope of this starter / boilerplate. One should remove the dependency to `stylelint` and drop the file `.stylelintrc`. I guess this is a leftover from the starter this starter was forked from. In order to avoid this kind of question in the future, all mention of `stylelint` should be purged from the source. How you lint your styles is not important to show people how to build a documentation static webpage with gatsby.

**Comment by levino** [comment]
IMO Issue can be closed as wontfix.

**Comment by zenflow** [comment]
@ericwindmill I got the answer but I think this is still unresolved because as @Levino said:

> One should remove the dependency to stylelint and drop the file .stylelintrc.

**Comment by levino** [comment]
Or a new issue should be created...

**Comment by zenflow** [comment]
@Levino Even better.. Created #20.. Thanks @Levino!
